version: '3.8'

services:
  influxdb:
    image: influxdb:3-core
    container_name: influxdb
    ports:
      - "8181:8181"
    volumes:
      - influxdb-data:/var/lib/influxdb3
    user: root
    command: influxdb3 serve --node-id node0 --object-store file --data-dir /var/lib/influxdb3
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  influxdb-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/db/influx
      o: bind

  timescale-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/db/timescale
      o: bind
